apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 1
images:
- name: schoolofdevops/vote
  newName: alexlek/vote
  newTag: main-0fcc5f1e-1758921430 #{"$imagepolicy":"flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@sre.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
